# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


from ..images import image_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(757, 539)
        Dialog.setMinimumSize(QtCore.QSize(710, 530))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/QQ (6).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.displayLayout = QtWidgets.QVBoxLayout()
        self.displayLayout.setContentsMargins(-1, -1, -1, 0)
        self.displayLayout.setSpacing(0)
        self.displayLayout.setObjectName("displayLayout")
        self.displayView = QtWidgets.QFrame(Dialog)
        self.displayView.setMinimumSize(QtCore.QSize(700, 300))
        self.displayView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.displayView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.displayView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.displayView.setObjectName("displayView")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.displayView)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chatwin = QtWidgets.QScrollArea(self.displayView)
        self.chatwin.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.chatwin.setStyleSheet("border:none;")
        self.chatwin.setWidgetResizable(True)
        self.chatwin.setObjectName("chatwin")
        self.chatscrollArea = QtWidgets.QWidget()
        self.chatscrollArea.setGeometry(QtCore.QRect(0, 0, 753, 355))
        self.chatscrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chatscrollArea.setObjectName("chatscrollArea")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.chatscrollArea)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 165, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.chatwin.setWidget(self.chatscrollArea)
        self.verticalLayout.addWidget(self.chatwin)
        self.displayLayout.addWidget(self.displayView)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-top:1px solid lightgray;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(10, 5, 10, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.biaoqing = QtWidgets.QPushButton(self.groupBox)
        self.biaoqing.setStyleSheet("border:none;background:none;")
        self.biaoqing.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/QQ (12).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.biaoqing.setIcon(icon1)
        self.biaoqing.setIconSize(QtCore.QSize(25, 25))
        self.biaoqing.setObjectName("biaoqing")
        self.horizontalLayout.addWidget(self.biaoqing)
        self.font = QtWidgets.QPushButton(self.groupBox)
        self.font.setStyleSheet("border:none;background:none;")
        self.font.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/QQ (14).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.font.setIcon(icon2)
        self.font.setIconSize(QtCore.QSize(25, 25))
        self.font.setObjectName("font")
        self.horizontalLayout.addWidget(self.font)
        self.music = QtWidgets.QPushButton(self.groupBox)
        self.music.setStyleSheet("border:none;background:none;")
        self.music.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/QQ (15).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.music.setIcon(icon3)
        self.music.setIconSize(QtCore.QSize(25, 25))
        self.music.setObjectName("music")
        self.horizontalLayout.addWidget(self.music)
        self.file = QtWidgets.QPushButton(self.groupBox)
        self.file.setStyleSheet("border:none;background:none;")
        self.file.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/QQ (18).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file.setIcon(icon4)
        self.file.setIconSize(QtCore.QSize(25, 25))
        self.file.setObjectName("file")
        self.horizontalLayout.addWidget(self.file)
        self.picture = QtWidgets.QPushButton(self.groupBox)
        self.picture.setStyleSheet("border:none;background:none;")
        self.picture.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/QQ (21).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture.setIcon(icon5)
        self.picture.setIconSize(QtCore.QSize(25, 25))
        self.picture.setObjectName("picture")
        self.horizontalLayout.addWidget(self.picture)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.chatrecord = QtWidgets.QPushButton(self.groupBox)
        self.chatrecord.setStyleSheet("border:none;\n"
"background:none;")
        self.chatrecord.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/QQ (13).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chatrecord.setIcon(icon6)
        self.chatrecord.setIconSize(QtCore.QSize(25, 25))
        self.chatrecord.setObjectName("chatrecord")
        self.horizontalLayout.addWidget(self.chatrecord)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.displayLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(700, 100))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.frame)

        self.textEdit.acceptRichText()
        self.textEdit.setStyleSheet("border:none;")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.displayLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 15, 0)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.closechat = QtWidgets.QPushButton(self.frame_3)
        self.closechat.setMinimumSize(QtCore.QSize(90, 30))
        self.closechat.setMaximumSize(QtCore.QSize(90, 30))
        self.closechat.setStyleSheet("border:1px solid lightgray;")
        self.closechat.setObjectName("closechat")
        self.horizontalLayout_3.addWidget(self.closechat)
        self.send = QtWidgets.QPushButton(self.frame_3)
        self.send.setMinimumSize(QtCore.QSize(90, 30))
        self.send.setMaximumSize(QtCore.QSize(90, 30))
        self.send.setStyleSheet("border:1px solid lightgray;\n"
"background-color: rgb(57, 219, 255);\n"
"color: rgb(255, 255, 255);")
        self.send.setObjectName("send")
        self.horizontalLayout_3.addWidget(self.send)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.displayLayout.addWidget(self.frame_3)
        self.verticalLayout_5.addLayout(self.displayLayout)

        self.retranslateUi(Dialog)
        self.send.clicked.connect(Dialog.sendmsg)
        self.send.clicked.connect(self.textEdit.clear)
        self.closechat.clicked.connect(Dialog.close)
        self.biaoqing.clicked.connect(Dialog.choseExpress)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.closechat.setText(_translate("Dialog", "关闭"))
        self.send.setText(_translate("Dialog", "发送"))

