# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

from ..images import image_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(360, 829)
        Form.setMinimumSize(QtCore.QSize(300, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 120))
        self.frame.setStyleSheet("background-color: rgb(34, 189, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.usrPic = QtWidgets.QLabel(self.frame)
        self.usrPic.setGeometry(QtCore.QRect(30, 30, 60, 60))
        self.usrPic.setText("")
        self.usrPic.setPixmap(QtGui.QPixmap(":/image/QQ (1).png"))
        self.usrPic.setScaledContents(True)
        self.usrPic.setObjectName("usrPic")
        self.Name = QtWidgets.QLabel(self.frame)
        self.Name.setGeometry(QtCore.QRect(100, 40, 300, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Name.setFont(font)
        self.Name.setStyleSheet("color: rgb(255, 255, 255);")
        self.Name.setObjectName("Name")
        self.autoGraph = QtWidgets.QLabel(self.frame)
        self.autoGraph.setGeometry(QtCore.QRect(100, 65, 300, 15))
        self.autoGraph.setStyleSheet("color: rgb(255, 255, 255);")
        self.autoGraph.setTextFormat(QtCore.Qt.AutoText)
        self.autoGraph.setScaledContents(True)
        self.autoGraph.setWordWrap(True)
        self.autoGraph.setObjectName("autoGraph")
        self.closeBtn = QtWidgets.QPushButton(self.frame)
        self.closeBtn.setGeometry(QtCore.QRect(330, 10, 20, 20))
        self.closeBtn.setStyleSheet("border:0;\n"
"background:none;\n"
"")
        self.closeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon)
        self.closeBtn.setObjectName("closeBtn")
        self.zoomIn = QtWidgets.QPushButton(self.frame)
        self.zoomIn.setGeometry(QtCore.QRect(280, 10, 20, 20))
        self.zoomIn.setStyleSheet("border:0;\n"
"background:none;\n"
"")
        self.zoomIn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomIn.setIcon(icon1)
        self.zoomIn.setFlat(False)
        self.zoomIn.setObjectName("zoomIn")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setStyleSheet("border:none;\n"
"background-color: rgb(255, 255, 255);")
        self.tab1.setObjectName("tab1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab1)
        self.scrollArea_3.setStyleSheet("")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 354, 670))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.setContentsMargins(7, 0, 7, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.addWidget(self.scrollArea_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/lianxi3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab1, icon2, "最近联系")
        self.tab2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tab2.setFont(font)
        self.tab2.setStyleSheet("border:none;\n"
"background-color: rgb(255, 255, 255);")
        self.tab2.setObjectName("tab2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(2, -1, 2, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("border:none")
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setLineWidth(0)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 86, 85))
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setContentsMargins(0, 0, 1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 85, 85))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/QQ4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 352, 614))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 351, 614))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setContentsMargins(7, 0, 7, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/unlog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_2, icon4, "")
        self.horizontalLayout_3.addWidget(self.toolBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/lianxi2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab2, icon5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.searchBtn = QtWidgets.QPushButton(self.tab)
        self.searchBtn.setGeometry(QtCore.QRect(270, 30, 71, 31))
        self.searchBtn.setStyleSheet("border-radius:5px;color:white;\n"
"background-color: rgb(55, 185, 255);")
        self.searchBtn.setObjectName("searchBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(100, 30, 161, 31))
        self.lineEdit.setStyleSheet("border:1px solid lightgray;")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.listView = QtWidgets.QListView(self.tab)
        self.listView.setGeometry(QtCore.QRect(100, 120, 241, 331))
        self.listView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listView.setWordWrap(True)
        self.listView.setObjectName("listView")
        self.add = QtWidgets.QPushButton(self.tab)
        self.add.setGeometry(QtCore.QRect(270, 70, 71, 31))
        self.add.setStyleSheet("border-radius:5px;color:white;\n"
"background-color: rgb(55, 185, 255);")
        self.add.setObjectName("add")
        self.selectUsr = QtWidgets.QLabel(self.tab)
        self.selectUsr.setGeometry(QtCore.QRect(100, 70, 161, 31))
        self.selectUsr.setStyleSheet("border-bottom: 1px solid lightgray;;\n"
"")
        self.selectUsr.setText("")
        self.selectUsr.setObjectName("selectUsr")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 40, 50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/image/search2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/jiahao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon6, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(0)
        self.closeBtn.clicked.connect(Form.close)
        self.zoomIn.clicked.connect(Form.showMinimized)
        self.searchBtn.clicked.connect(Form.search)
        self.add.clicked.connect(Form.add)
        self.lineEdit.textEdited['QString'].connect(Form.searchUsr)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QQ"))
        self.Name.setText(_translate("Form", "mike"))
        self.autoGraph.setText(_translate("Form", "这个人很懒，什么也没有留下"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "我的好友"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Form", "黑名单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "我的好友"))
        self.searchBtn.setText(_translate("Form", "搜索"))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入昵称"))
        self.add.setText(_translate("Form", "添加"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "添加好友"))

