
# Form implementation generated from reading ui file 'regWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from ..images import image_rc

class Ui_regUI(object):
    def setupUi(self, regUI):
        regUI.setObjectName("regUI")
        regUI.resize(498, 435)
        self.label_2 = QtWidgets.QLabel(regUI)
        self.label_2.setGeometry(QtCore.QRect(215, 90, 70, 70))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/QQ2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.closeBtn = QtWidgets.QPushButton(regUI)
        self.closeBtn.setGeometry(QtCore.QRect(460, 10, 20, 20))
        self.closeBtn.setStyleSheet("border:0;\n"
"background:none;\n"
"")
        self.closeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon)
        self.closeBtn.setObjectName("closeBtn")
        self.usrPwd = QtWidgets.QLineEdit(regUI)
        self.usrPwd.setGeometry(QtCore.QRect(102, 223, 300, 35))
        self.usrPwd.setStyleSheet("padding-left:33;\n"
"border:none;")
        self.usrPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.usrPwd.setClearButtonEnabled(True)
        self.usrPwd.setObjectName("usrPwd")
        self.buttonBox = QtWidgets.QDialogButtonBox(regUI)
        self.buttonBox.setGeometry(QtCore.QRect(221, 390, 181, 30))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(regUI)
        self.pushButton.setGeometry(QtCore.QRect(420, 175, 60, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border:0;\n"
"background:none;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pwdIcon = QtWidgets.QLabel(regUI)
        self.pwdIcon.setGeometry(QtCore.QRect(109, 230, 20, 20))
        self.pwdIcon.setText("")
        self.pwdIcon.setPixmap(QtGui.QPixmap(":/image/pwdIcon.png"))
        self.pwdIcon.setScaledContents(True)
        self.pwdIcon.setObjectName("pwdIcon")
        self.usrPwd_2 = QtWidgets.QLineEdit(regUI)
        self.usrPwd_2.setGeometry(QtCore.QRect(102, 273, 300, 35))
        self.usrPwd_2.setStyleSheet("padding-left:33;\n"
"border:none;")
        self.usrPwd_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.usrPwd_2.setClearButtonEnabled(True)
        self.usrPwd_2.setObjectName("usrPwd_2")
        self.usrName = QtWidgets.QLineEdit(regUI)
        self.usrName.setGeometry(QtCore.QRect(102, 175, 300, 35))
        self.usrName.setStyleSheet("padding-left:33;\n"
"border:none;")
        self.usrName.setInputMask("")
        self.usrName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.usrName.setClearButtonEnabled(True)
        self.usrName.setObjectName("usrName")
        self.topPic = QtWidgets.QLabel(regUI)
        self.topPic.setGeometry(QtCore.QRect(0, 0, 500, 131))
        self.topPic.setText("")
        self.topPic.setPixmap(QtGui.QPixmap(":/image/mainBackPic.png"))
        self.topPic.setScaledContents(False)
        self.topPic.setObjectName("topPic")
        self.pwdIcon_2 = QtWidgets.QLabel(regUI)
        self.pwdIcon_2.setGeometry(QtCore.QRect(109, 280, 20, 20))
        self.pwdIcon_2.setText("")
        self.pwdIcon_2.setPixmap(QtGui.QPixmap(":/image/pwdIcon.png"))
        self.pwdIcon_2.setScaledContents(True)
        self.pwdIcon_2.setObjectName("pwdIcon_2")
        self.usrIcon = QtWidgets.QLabel(regUI)
        self.usrIcon.setGeometry(QtCore.QRect(107, 180, 25, 25))
        self.usrIcon.setText("")
        self.usrIcon.setPixmap(QtGui.QPixmap(":/image/unlog.png"))
        self.usrIcon.setScaledContents(True)
        self.usrIcon.setObjectName("usrIcon")
        self.zoomIn = QtWidgets.QPushButton(regUI)
        self.zoomIn.setGeometry(QtCore.QRect(420, 10, 20, 20))
        self.zoomIn.setStyleSheet("border:0;\n"
"background:none;\n"
"")
        self.zoomIn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomIn.setIcon(icon1)
        self.zoomIn.setFlat(False)
        self.zoomIn.setObjectName("zoomIn")
        self.radioman = QtWidgets.QRadioButton(regUI)
        self.radioman.setGeometry(QtCore.QRect(210, 330, 61, 19))
        self.radioman.setChecked(True)
        self.radioman.setObjectName("radioman")
        self.radiowen = QtWidgets.QRadioButton(regUI)
        self.radiowen.setGeometry(QtCore.QRect(290, 330, 71, 19))
        self.radiowen.setObjectName("radiowen")
        self.label = QtWidgets.QLabel(regUI)
        self.label.setGeometry(QtCore.QRect(110, 320, 61, 35))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(90, 90, 90);")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.topPic.raise_()
        self.label_2.raise_()
        self.closeBtn.raise_()
        self.usrPwd.raise_()
        self.buttonBox.raise_()
        self.pushButton.raise_()
        self.pwdIcon.raise_()
        self.usrPwd_2.raise_()
        self.usrName.raise_()
        self.pwdIcon_2.raise_()
        self.usrIcon.raise_()
        self.zoomIn.raise_()
        self.radioman.raise_()
        self.radiowen.raise_()
        self.label.raise_()

        self.retranslateUi(regUI)
        self.buttonBox.accepted.connect(regUI.accept)
        self.buttonBox.rejected.connect(regUI.reject)
        self.zoomIn.clicked.connect(regUI.showMinimized)
        self.closeBtn.clicked.connect(regUI.close)
        self.usrName.editingFinished.connect(regUI.getName)
        self.usrPwd.editingFinished.connect(regUI.firstPwd)
        self.usrPwd_2.editingFinished.connect(regUI.secondPwd)
        QtCore.QMetaObject.connectSlotsByName(regUI)

    def retranslateUi(self, regUI):
        _translate = QtCore.QCoreApplication.translate
        regUI.setWindowTitle(_translate("regUI", "Dialog"))
        self.usrPwd.setPlaceholderText(_translate("regUI", "密码"))
        self.usrPwd_2.setPlaceholderText(_translate("regUI", "确认密码"))
        self.usrName.setPlaceholderText(_translate("regUI", "QQ号码/手机号/邮箱"))
        self.radioman.setText(_translate("regUI", "男"))
        self.radiowen.setText(_translate("regUI", "女"))
        self.label.setText(_translate("regUI", "性  别"))

